export type Subject = {
  id: string;
  name: string;
  meta: string;
  category: string;
  topics: string[];
};

const catalog: Record<string, string[]> = {
  "Maths & Statistics": [
    "Pure Mathematics",
    "Further Mathematics",
    "Algebra I",
    "Algebra II",
    "Linear Algebra",
    "Abstract Algebra",
    "Geometry",
    "Trigonometry",
    "Pre-Calculus",
    "Calculus I",
    "Calculus II",
    "Multivariable Calculus",
    "Differential Equations",
    "Discrete Mathematics",
    "Number Theory",
    "Real Analysis",
    "Complex Analysis",
    "Numerical Methods",
    "Probability",
    "Statistics",
    "Statistical Inference",
    "Regression Analysis",
    "Time Series Analysis",
    "Operations Research",
    "Mathematical Logic",
  ],
  "Sciences": [
    "Biology",
    "Human Physiology",
    "Human Anatomy",
    "Cell Biology",
    "Genetics",
    "Molecular Biology",
    "Microbiology",
    "Immunology",
    "Biochemistry",
    "Botany",
    "Zoology",
    "Ecology",
    "Evolutionary Biology",
    "Neuroscience",
    "Chemistry",
    "Organic Chemistry",
    "Inorganic Chemistry",
    "Physical Chemistry",
    "Analytical Chemistry",
    "Physics",
    "Classical Mechanics",
    "Electromagnetism",
    "Thermodynamics",
    "Quantum Physics",
    "Optics",
    "Astronomy",
    "Astrophysics",
    "Geology",
    "Environmental Science",
    "Climate Science",
    "Materials Science",
    "Pharmacology",
    "Pathology",
    "Nutrition Science",
    "Sports Science",
  ],
  "Technology & Engineering": [
    "Computer Science",
    "Programming Fundamentals",
    "Data Structures",
    "Algorithms",
    "Object-Oriented Programming",
    "Web Development",
    "Mobile Development",
    "Databases",
    "Operating Systems",
    "Computer Networks",
    "Computer Architecture",
    "Software Engineering",
    "Cybersecurity",
    "Cryptography",
    "Machine Learning",
    "Deep Learning",
    "Artificial Intelligence",
    "Data Science",
    "Cloud Computing",
    "DevOps",
    "Information Systems",
    "Robotics",
    "Mechanical Engineering",
    "Electrical Engineering",
    "Electronics",
    "Civil Engineering",
    "Structural Analysis",
    "Chemical Engineering",
    "Aerospace Engineering",
    "Biomedical Engineering",
    "Control Systems",
    "Signal Processing",
    "Fluid Mechanics",
    "Engineering Drawing",
    "Technical Design",
  ],
  "Business & Economics": [
    "Economics",
    "Microeconomics",
    "Macroeconomics",
    "Behavioral Economics",
    "Development Economics",
    "Econometrics",
    "Business Studies",
    "Accounting",
    "Financial Accounting",
    "Management Accounting",
    "Auditing",
    "Corporate Finance",
    "Investment Analysis",
    "Banking and Finance",
    "Taxation",
    "Marketing",
    "Digital Marketing",
    "Consumer Behaviour",
    "Entrepreneurship",
    "Management",
    "Human Resource Management",
    "Organisational Behaviour",
    "Operations Management",
    "Supply Chain Management",
    "Project Management",
    "International Trade",
    "Commerce",
    "Insurance",
    "Real Estate",
    "Business Law",
  ],
  "Humanities": [
    "World History",
    "Ancient History",
    "Modern History",
    "African History",
    "European History",
    "American History",
    "Art History",
    "Philosophy",
    "Ethics",
    "Logic",
    "Religious Studies",
    "Theology",
    "Classical Studies",
    "Archaeology",
    "Anthropology",
    "Cultural Studies",
    "Museum Studies",
    "Musicology",
  ],
  "Languages & Literature": [
    "English Language",
    "English Literature",
    "Creative Writing",
    "Academic Writing",
    "Linguistics",
    "Phonetics",
    "Literary Theory",
    "Poetry",
    "Drama",
    "Comparative Literature",
    "French",
    "Spanish",
    "German",
    "Italian",
    "Portuguese",
    "Mandarin Chinese",
    "Japanese",
    "Korean",
    "Arabic",
    "Latin",
    "Greek",
    "Swahili",
    "Hindi",
    "Russian",
    "Sign Language",
    "Translation Studies",
  ],
  "Social Sciences": [
    "Psychology",
    "Cognitive Psychology",
    "Developmental Psychology",
    "Social Psychology",
    "Abnormal Psychology",
    "Sociology",
    "Political Science",
    "International Relations",
    "Public Policy",
    "Public Administration",
    "Law",
    "Constitutional Law",
    "Criminal Law",
    "Criminology",
    "Human Geography",
    "Physical Geography",
    "Urban Planning",
    "Demography",
    "Social Work",
    "Gender Studies",
    "Media Studies",
    "Journalism",
    "Communication Studies",
    "Education Studies",
    "Educational Psychology",
    "Curriculum Studies",
  ],
  "Health & Medicine": [
    "Medicine",
    "Nursing",
    "Midwifery",
    "Public Health",
    "Epidemiology",
    "Dentistry",
    "Pharmacy",
    "Physiotherapy",
    "Radiography",
    "Medical Laboratory Science",
    "Optometry",
    "Veterinary Science",
    "Occupational Therapy",
    "Mental Health Care",
    "First Aid and Emergency Care",
    "Health Informatics",
  ],
  "Creative & Applied": [
    "Fine Art",
    "Graphic Design",
    "Product Design",
    "Architecture",
    "Interior Design",
    "Fashion Design",
    "Photography",
    "Film Studies",
    "Animation",
    "Music Theory",
    "Music Performance",
    "Sound Engineering",
    "Theatre Studies",
    "Dance",
    "Culinary Arts",
    "Hospitality Management",
    "Tourism Management",
    "Agriculture",
    "Horticulture",
    "Food Science",
  ],
};

const topicTemplates = [
  "Foundations and key vocabulary",
  "Core principles and models",
  "Methods and problem solving",
  "Applied examples and case studies",
  "Common exam question types",
  "Data, evidence and interpretation",
  "Advanced topics and extensions",
  "Revision, recall and exam technique",
];

function slug(name: string) {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

export const categories = Object.keys(catalog);

export const subjects: Subject[] = categories.flatMap((category) =>
  catalog[category]!.map((name) => ({
    id: slug(name),
    name,
    category,
    meta: `${topicTemplates.length} topics · ${category}`,
    topics: topicTemplates.map((template) => `${name}: ${template}`),
  })),
);

export function findSubject(id: string | null) {
  return subjects.find((subject) => subject.id === id) ?? null;
}
