/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ArcadeRouteImport } from './routes/arcade'
import { Route as AssignmentsRouteImport } from './routes/assignments'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CustomerServiceRouteImport } from './routes/customer-service'
import { Route as FlashcardsRouteImport } from './routes/flashcards'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as PastQuestionsRouteImport } from './routes/past-questions'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as QuizzesRouteImport } from './routes/quizzes'
import { Route as RecordLectureRouteImport } from './routes/record-lecture'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StudyPlanRouteImport } from './routes/study-plan'
import { Route as SyllabusRouteImport } from './routes/syllabus'
import { Route as SyllabusNotesRouteImport } from './routes/syllabus-notes'
import { Route as TestRouteImport } from './routes/test'
import { Route as TutorsRouteImport } from './routes/tutors'
import { Route as ApiAssignmentRouteImport } from './routes/api/assignment'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiPaypalCaptureRouteImport } from './routes/api/paypal-capture'
import { Route as ApiPaypalOrderRouteImport } from './routes/api/paypal-order'
import { Route as OnboardingGoalRouteImport } from './routes/onboarding.goal'
import { Route as OnboardingRoleRouteImport } from './routes/onboarding.role'
import { Route as OnboardingSourceRouteImport } from './routes/onboarding.source'
import { Route as ApiV1ChatCompletionsRouteImport } from './routes/api/v1/chat/completions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ArcadeRoute = ArcadeRouteImport.update({
  id: '/arcade',
  path: '/arcade',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsRoute = AssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerServiceRoute = CustomerServiceRouteImport.update({
  id: '/customer-service',
  path: '/customer-service',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsRoute = FlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const PastQuestionsRoute = PastQuestionsRouteImport.update({
  id: '/past-questions',
  path: '/past-questions',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesRoute = QuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordLectureRoute = RecordLectureRouteImport.update({
  id: '/record-lecture',
  path: '/record-lecture',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyPlanRoute = StudyPlanRouteImport.update({
  id: '/study-plan',
  path: '/study-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const SyllabusRoute = SyllabusRouteImport.update({
  id: '/syllabus',
  path: '/syllabus',
  getParentRoute: () => rootRouteImport,
} as any)
const SyllabusNotesRoute = SyllabusNotesRouteImport.update({
  id: '/syllabus-notes',
  path: '/syllabus-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorsRoute = TutorsRouteImport.update({
  id: '/tutors',
  path: '/tutors',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssignmentRoute = ApiAssignmentRouteImport.update({
  id: '/api/assignment',
  path: '/api/assignment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaypalCaptureRoute = ApiPaypalCaptureRouteImport.update({
  id: '/api/paypal-capture',
  path: '/api/paypal-capture',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaypalOrderRoute = ApiPaypalOrderRouteImport.update({
  id: '/api/paypal-order',
  path: '/api/paypal-order',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingGoalRoute = OnboardingGoalRouteImport.update({
  id: '/onboarding/goal',
  path: '/onboarding/goal',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoleRoute = OnboardingRoleRouteImport.update({
  id: '/onboarding/role',
  path: '/onboarding/role',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingSourceRoute = OnboardingSourceRouteImport.update({
  id: '/onboarding/source',
  path: '/onboarding/source',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ChatCompletionsRoute = ApiV1ChatCompletionsRouteImport.update({
  id: '/api/v1/chat/completions',
  path: '/api/v1/chat/completions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/admin': typeof AdminRoute
  '/arcade': typeof ArcadeRoute
  '/assignments': typeof AssignmentsRoute
  '/calendar': typeof CalendarRoute
  '/chat': typeof ChatRoute
  '/checkout': typeof CheckoutRoute
  '/customer-service': typeof CustomerServiceRoute
  '/flashcards': typeof FlashcardsRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/past-questions': typeof PastQuestionsRoute
  '/pricing': typeof PricingRoute
  '/quizzes': typeof QuizzesRoute
  '/record-lecture': typeof RecordLectureRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/study-plan': typeof StudyPlanRoute
  '/syllabus': typeof SyllabusRoute
  '/syllabus-notes': typeof SyllabusNotesRoute
  '/test': typeof TestRoute
  '/tutors': typeof TutorsRoute
  '/api/assignment': typeof ApiAssignmentRoute
  '/api/chat': typeof ApiChatRoute
  '/api/paypal-capture': typeof ApiPaypalCaptureRoute
  '/api/paypal-order': typeof ApiPaypalOrderRoute
  '/onboarding/goal': typeof OnboardingGoalRoute
  '/onboarding/role': typeof OnboardingRoleRoute
  '/onboarding/source': typeof OnboardingSourceRoute
  '/api/v1/chat/completions': typeof ApiV1ChatCompletionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/admin': typeof AdminRoute
  '/arcade': typeof ArcadeRoute
  '/assignments': typeof AssignmentsRoute
  '/calendar': typeof CalendarRoute
  '/chat': typeof ChatRoute
  '/checkout': typeof CheckoutRoute
  '/customer-service': typeof CustomerServiceRoute
  '/flashcards': typeof FlashcardsRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/past-questions': typeof PastQuestionsRoute
  '/pricing': typeof PricingRoute
  '/quizzes': typeof QuizzesRoute
  '/record-lecture': typeof RecordLectureRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/study-plan': typeof StudyPlanRoute
  '/syllabus': typeof SyllabusRoute
  '/syllabus-notes': typeof SyllabusNotesRoute
  '/test': typeof TestRoute
  '/tutors': typeof TutorsRoute
  '/api/assignment': typeof ApiAssignmentRoute
  '/api/chat': typeof ApiChatRoute
  '/api/paypal-capture': typeof ApiPaypalCaptureRoute
  '/api/paypal-order': typeof ApiPaypalOrderRoute
  '/onboarding/goal': typeof OnboardingGoalRoute
  '/onboarding/role': typeof OnboardingRoleRoute
  '/onboarding/source': typeof OnboardingSourceRoute
  '/api/v1/chat/completions': typeof ApiV1ChatCompletionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/admin': typeof AdminRoute
  '/arcade': typeof ArcadeRoute
  '/assignments': typeof AssignmentsRoute
  '/calendar': typeof CalendarRoute
  '/chat': typeof ChatRoute
  '/checkout': typeof CheckoutRoute
  '/customer-service': typeof CustomerServiceRoute
  '/flashcards': typeof FlashcardsRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/past-questions': typeof PastQuestionsRoute
  '/pricing': typeof PricingRoute
  '/quizzes': typeof QuizzesRoute
  '/record-lecture': typeof RecordLectureRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/study-plan': typeof StudyPlanRoute
  '/syllabus': typeof SyllabusRoute
  '/syllabus-notes': typeof SyllabusNotesRoute
  '/test': typeof TestRoute
  '/tutors': typeof TutorsRoute
  '/api/assignment': typeof ApiAssignmentRoute
  '/api/chat': typeof ApiChatRoute
  '/api/paypal-capture': typeof ApiPaypalCaptureRoute
  '/api/paypal-order': typeof ApiPaypalOrderRoute
  '/onboarding/goal': typeof OnboardingGoalRoute
  '/onboarding/role': typeof OnboardingRoleRoute
  '/onboarding/source': typeof OnboardingSourceRoute
  '/api/v1/chat/completions': typeof ApiV1ChatCompletionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/admin'
    | '/arcade'
    | '/assignments'
    | '/calendar'
    | '/chat'
    | '/checkout'
    | '/customer-service'
    | '/flashcards'
    | '/home'
    | '/login'
    | '/notes'
    | '/past-questions'
    | '/pricing'
    | '/quizzes'
    | '/record-lecture'
    | '/settings'
    | '/signup'
    | '/study-plan'
    | '/syllabus'
    | '/syllabus-notes'
    | '/test'
    | '/tutors'
    | '/api/assignment'
    | '/api/chat'
    | '/api/paypal-capture'
    | '/api/paypal-order'
    | '/onboarding/goal'
    | '/onboarding/role'
    | '/onboarding/source'
    | '/api/v1/chat/completions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/admin'
    | '/arcade'
    | '/assignments'
    | '/calendar'
    | '/chat'
    | '/checkout'
    | '/customer-service'
    | '/flashcards'
    | '/home'
    | '/login'
    | '/notes'
    | '/past-questions'
    | '/pricing'
    | '/quizzes'
    | '/record-lecture'
    | '/settings'
    | '/signup'
    | '/study-plan'
    | '/syllabus'
    | '/syllabus-notes'
    | '/test'
    | '/tutors'
    | '/api/assignment'
    | '/api/chat'
    | '/api/paypal-capture'
    | '/api/paypal-order'
    | '/onboarding/goal'
    | '/onboarding/role'
    | '/onboarding/source'
    | '/api/v1/chat/completions'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/admin'
    | '/arcade'
    | '/assignments'
    | '/calendar'
    | '/chat'
    | '/checkout'
    | '/customer-service'
    | '/flashcards'
    | '/home'
    | '/login'
    | '/notes'
    | '/past-questions'
    | '/pricing'
    | '/quizzes'
    | '/record-lecture'
    | '/settings'
    | '/signup'
    | '/study-plan'
    | '/syllabus'
    | '/syllabus-notes'
    | '/test'
    | '/tutors'
    | '/api/assignment'
    | '/api/chat'
    | '/api/paypal-capture'
    | '/api/paypal-order'
    | '/onboarding/goal'
    | '/onboarding/role'
    | '/onboarding/source'
    | '/api/v1/chat/completions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  AdminRoute: typeof AdminRoute
  ArcadeRoute: typeof ArcadeRoute
  AssignmentsRoute: typeof AssignmentsRoute
  CalendarRoute: typeof CalendarRoute
  ChatRoute: typeof ChatRoute
  CheckoutRoute: typeof CheckoutRoute
  CustomerServiceRoute: typeof CustomerServiceRoute
  FlashcardsRoute: typeof FlashcardsRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  NotesRoute: typeof NotesRoute
  PastQuestionsRoute: typeof PastQuestionsRoute
  PricingRoute: typeof PricingRoute
  QuizzesRoute: typeof QuizzesRoute
  RecordLectureRoute: typeof RecordLectureRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  StudyPlanRoute: typeof StudyPlanRoute
  SyllabusRoute: typeof SyllabusRoute
  SyllabusNotesRoute: typeof SyllabusNotesRoute
  TestRoute: typeof TestRoute
  TutorsRoute: typeof TutorsRoute
  ApiAssignmentRoute: typeof ApiAssignmentRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiPaypalCaptureRoute: typeof ApiPaypalCaptureRoute
  ApiPaypalOrderRoute: typeof ApiPaypalOrderRoute
  OnboardingGoalRoute: typeof OnboardingGoalRoute
  OnboardingRoleRoute: typeof OnboardingRoleRoute
  OnboardingSourceRoute: typeof OnboardingSourceRoute
  ApiV1ChatCompletionsRoute: typeof ApiV1ChatCompletionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arcade': {
      id: '/arcade'
      path: '/arcade'
      fullPath: '/arcade'
      preLoaderRoute: typeof ArcadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments': {
      id: '/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-service': {
      id: '/customer-service'
      path: '/customer-service'
      fullPath: '/customer-service'
      preLoaderRoute: typeof CustomerServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards': {
      id: '/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof FlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/past-questions': {
      id: '/past-questions'
      path: '/past-questions'
      fullPath: '/past-questions'
      preLoaderRoute: typeof PastQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes': {
      id: '/quizzes'
      path: '/quizzes'
      fullPath: '/quizzes'
      preLoaderRoute: typeof QuizzesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/record-lecture': {
      id: '/record-lecture'
      path: '/record-lecture'
      fullPath: '/record-lecture'
      preLoaderRoute: typeof RecordLectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-plan': {
      id: '/study-plan'
      path: '/study-plan'
      fullPath: '/study-plan'
      preLoaderRoute: typeof StudyPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/syllabus': {
      id: '/syllabus'
      path: '/syllabus'
      fullPath: '/syllabus'
      preLoaderRoute: typeof SyllabusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/syllabus-notes': {
      id: '/syllabus-notes'
      path: '/syllabus-notes'
      fullPath: '/syllabus-notes'
      preLoaderRoute: typeof SyllabusNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutors': {
      id: '/tutors'
      path: '/tutors'
      fullPath: '/tutors'
      preLoaderRoute: typeof TutorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assignment': {
      id: '/api/assignment'
      path: '/api/assignment'
      fullPath: '/api/assignment'
      preLoaderRoute: typeof ApiAssignmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paypal-capture': {
      id: '/api/paypal-capture'
      path: '/api/paypal-capture'
      fullPath: '/api/paypal-capture'
      preLoaderRoute: typeof ApiPaypalCaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paypal-order': {
      id: '/api/paypal-order'
      path: '/api/paypal-order'
      fullPath: '/api/paypal-order'
      preLoaderRoute: typeof ApiPaypalOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/goal': {
      id: '/onboarding/goal'
      path: '/onboarding/goal'
      fullPath: '/onboarding/goal'
      preLoaderRoute: typeof OnboardingGoalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/role': {
      id: '/onboarding/role'
      path: '/onboarding/role'
      fullPath: '/onboarding/role'
      preLoaderRoute: typeof OnboardingRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/source': {
      id: '/onboarding/source'
      path: '/onboarding/source'
      fullPath: '/onboarding/source'
      preLoaderRoute: typeof OnboardingSourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/chat/completions': {
      id: '/api/v1/chat/completions'
      path: '/api/v1/chat/completions'
      fullPath: '/api/v1/chat/completions'
      preLoaderRoute: typeof ApiV1ChatCompletionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  AdminRoute: AdminRoute,
  ArcadeRoute: ArcadeRoute,
  AssignmentsRoute: AssignmentsRoute,
  CalendarRoute: CalendarRoute,
  ChatRoute: ChatRoute,
  CheckoutRoute: CheckoutRoute,
  CustomerServiceRoute: CustomerServiceRoute,
  FlashcardsRoute: FlashcardsRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  NotesRoute: NotesRoute,
  PastQuestionsRoute: PastQuestionsRoute,
  PricingRoute: PricingRoute,
  QuizzesRoute: QuizzesRoute,
  RecordLectureRoute: RecordLectureRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  StudyPlanRoute: StudyPlanRoute,
  SyllabusRoute: SyllabusRoute,
  SyllabusNotesRoute: SyllabusNotesRoute,
  TestRoute: TestRoute,
  TutorsRoute: TutorsRoute,
  ApiAssignmentRoute: ApiAssignmentRoute,
  ApiChatRoute: ApiChatRoute,
  ApiPaypalCaptureRoute: ApiPaypalCaptureRoute,
  ApiPaypalOrderRoute: ApiPaypalOrderRoute,
  OnboardingGoalRoute: OnboardingGoalRoute,
  OnboardingRoleRoute: OnboardingRoleRoute,
  OnboardingSourceRoute: OnboardingSourceRoute,
  ApiV1ChatCompletionsRoute: ApiV1ChatCompletionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
